WyvernLink/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.views.generic.base import RedirectView

import wl_profile2.urls as wl_profile
import wl_login.urls as wl_login

import wl_dashboard.urls as wl_dashboard

import wl_forum.urls as wl_forum
#>>>>>>> c9f8164b7e6d1029b3b68ef496fc1284e1179f51

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/',include(wl_login, namespace= 'login')),
    url(r'^profile/',include(wl_profile,namespace='profile')),
    url(r'^dashboard/',include(wl_dashboard, namespace= 'dashboard')),
    url(r'^forum/',include(wl_forum,namespace='forum')),

]

#>>>>>>> c9f8164b7e6d1029b3b68ef496fc1284e1179f51

wl_dashboard/urls.py
from django.conf.urls import url
from .views import *


urlpatterns = [
    url(r'^$', index, name='index'),

]

wl_forum/urls.py
from django.conf.urls import url
from .views import index,postContent,addComment,buildComment

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^postContent', postContent, name='postContent'),
    url(r'^addComment',addComment,name='addComment'),
url(r'^buildComment/(?P<post_id>[0-9]+)/$', addComment, name='buildComment'),


]

wl_login/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
    url(r'^$', index, name='index'),

]

wl_profile2/urls.py
from django.conf.urls import url
from .views import *


urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^createModel/$', createModel, name='createModel'),

]

wl_dashboard/models.py
from django.db import models

# Create your models here.

wl_forum/models.py
from django.db import models

# Create your models here.
class Forum(models.Model):
   # user_id = models.CharField(max_length=200)
    name = models.CharField(max_length=100)
    body = models.CharField(max_length=200)
    waktu = models.DateTimeField(auto_now_add=True)


class ForumComment(models.Model):
    body = models.CharField(max_length=400)
    forum = models.ForeignKey(Forum,on_delete=models.CASCADE)
    waktu = models.DateTimeField(auto_now_add=True)

wl_login/models.py
from django.db import models

# Create your models here.

wl_profile2/models.py
from django.db import models

class Company(models.Model):
    company_name = models.CharField(max_length=50)
    specialty = models.CharField(max_length=250)
    yearFounded = models.CharField(max_length=5)
    description = models.CharField(max_length=300)
    website = models.CharField(max_length=300)
    company_type = models.CharField(max_length=300)

wl_forum/forms.py
from django import forms


class PostingForm(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
    }
    attrs = {
        'type': 'text',
        'class': 'form-control',
        'placeholder': 'Write something ? '
    }
    tittle = forms.CharField(label='Tittle',required=True)
    content = forms.CharField(label='', required=True, widget=forms.Textarea(attrs=attrs))

class CommentForms(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
    }
    attrs = {
        'type': 'text',
        'class': 'form-control',
        'placeholder': 'Write something ? ',
        'rows' : '3',
        'cols': '3'
    }
    content = forms.CharField(label='Content', required=True,widget=forms.Textarea(attrs=attrs))

wl_dashboard/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    html ='dashboard/index.html'
    return render(request, html)

wl_forum/views.py
from django.shortcuts import render,HttpResponseRedirect
from .forms import PostingForm,CommentForms
from .models import Forum,ForumComment


# Create your views here.

response = {}
def index(request):
    post = Forum.objects.all()
    response['post'] = post
    html = 'wl_forum/wl_forum.html'
    response['form'] = PostingForm()
    posts = Forum.objects.all().order_by('waktu').reverse()
    response['posts'] = posts
    comments = ForumComment.objects.all().order_by('waktu').reverse()
    response['comments'] = comments
    response['commentsForm'] = CommentForms()
    return render(request, html, response)



def postContent(request):
    form =PostingForm(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            response['pesan'] = form.cleaned_data.get('content')
            response['tittle'] = form.cleaned_data.get('tittle')
            post = Forum(name=response['tittle'],body=response['pesan'])
            post.save()
            posts = Forum.objects.all().order_by('waktu').reverse()
            response['posts'] = posts
        return HttpResponseRedirect('/forum/')
    else:
        form = PostingForm()
        response['form'] = form
        posts = Forum.objects.all().order_by('waktu').reverse()
        response['posts'] = posts
        return HttpResponseRedirect('/forum/')


def addComment(request,post_id):
    form = CommentForms(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            response['pesan'] = form.cleaned_data.get('content')
            theForum = Forum.objects.get(id=post_id)
            post = ForumComment(body=response['pesan'],forum=theForum)
            post.save()
            comments = ForumComment.objects.all().order_by('waktu').reverse()
            response['comments'] = comments
        return HttpResponseRedirect('/forum/')
    else:
        form = CommentForms()
        response['commentsForm'] = form
        comments = ForumComment.objects.all().order_by('waktu').reverse()
        response['comments'] = comments
        return HttpResponseRedirect('/forum/')


def buildComment(request,post_id=None):
    addComment(request,post_id)

wl_login/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    response = response = {'name': 'Yazawa Nico', 'gender': 'Female', 'birthday': '22 July 1999', 'expertise':'Marketing','expertise1':'Controlling','expertise2':'Public Speaking',
                'description':'"Nico Nico-nii~ Anata no Heart ni Nico Nico-nii, "', 'email':'yazawa.nico@gmail.com',
                'pict':"https://manekin3k0.files.wordpress.com/2015/08/niconico.jpg?w=810"}
    html = 'wl_login.html'
    return render(request, html, response)

wl_profile2/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
from .models import Company
from django.core import serializers
import json

# Create your views here.
def index(request):
    html ='profile/profile.html'
    return render(request, html)

@csrf_exempt
def createModel(request):
    if request.method == 'POST':
        company_name = request.POST['name']
        specialty = request.POST['specialty']
        yearFounded = request.POST['year']
        description = request.POST['description']
        website = request.POST['website']
        company_type = request.POST['type']
        company = Company(company_name=company_name, specialty=specialty, yearFounded=yearFounded,description=description,website=website,company_type=company_type)
        company.save()
        data = model_to_dict(company)
        return HttpResponse(data)

def model_to_dict(obj):
    data = serializers.serialize('json', [obj, ])
    struct = json.loads(data)
    data = json.dumps(struct[0]["fields"])
    return data

wl_dashboard/templates/dashboard/index.html
{% load staticfiles %} {% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>HEHEHE | Dashboard</title>


    <script type="text/javascript" src="//platform.linkedin.com/in.js"> <!-- 814sv3y27px3b9 -->
          api_key: 818gaq2irb7wty
          authorize: false
          onLoad: onLinkedInLoad
          scope: r_basicprofile r_emailaddress rw_company_admin
        </script>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" />

    <!-- Custom fonts for this template -->
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}" />
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- Custom styles for this template -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/clean-blog.min.css' %}" />


      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <!-- <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" /> -->


    	<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800" rel="stylesheet">
    	<link href="https://fonts.googleapis.com/css?family=Montserrat:100,100i,200,200i,300,400,400i,500,500i,600,600i,700,700i,800" rel="stylesheet">

  </head>

  <body>


    <!-- Page Header -->
    <header class="masthead" style="background-image: url('img/home-bg.jpg')">
      <div class="overlay"></div>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <div class="site-heading">
              <h1>Job Seeker</h1>
              <span class="subheading">Best jobseeker in town</span>
            </div>
          </div>
        </div>
      </div>
      <center><script type="in/Login"></script></center>
      <script src="{% static 'js/login.js' %}"></script>
    </header>



    <!-- Main Content -->
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="post-preview">
            <a href="#">
              <h2 class="post-title">
                Misalkan ini lowongan 1
              </h2>
              <h3 class="post-subtitle">
                This is our job description
              </h3>
            </a>
            <p class="post-meta">Posted by
              <a href="#">Admin</a>
              on September 24, 2017</p>
          </div>
          <hr>
          <div class="post-preview">
            <a href="#">
              <h2 class="post-title">
                Misalkan ini lowongan 2
              </h2>
            </a>
            <p class="post-meta">Posted by
              <a href="#">Admin</a>
              on September 18, 2017</p>
          </div>
          <hr>
          <div class="post-preview">
            <a href="#.html">
              <h2 class="post-title">
                Misalkan ini lowongan 3
              </h2>
              <h3 class="post-subtitle">
                This is our job description
              </h3>
            </a>
            <p class="post-meta">Posted by
              <a href="#">Admin</a>
              on August 24, 2017</p>
          </div>

          <!-- Pager -->
          <div class="clearfix">
            <a class="btn btn-primary float-right" href="#">Older Posts &rarr;</a>
          </div>
        </div>
      </div>
    </div>

    <hr>

    <!-- Footer -->
    <footer>
        <p class="copyright text-muted">Copyright &copy; Edwin 2017</p>
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Custom scripts for this template -->
    <script src="static/js/clean-blog.min.js"></script>



    <!-- Jquery n Bootstrap Script -->
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
      <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
      {% block javascript %} {% endblock %}

  </body>

</html>

wl_forum/templates/wl_forum/wl_forum.html
<!DOCTYPE html>
<html lang="en">

     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <meta charset="UTF-8">
    {% block title %}
    <title>Write something</title>
    {% endblock %}
</head>
<body>
{% block content %}
<div class="container">
<form method="post" action="{% url 'forum:postContent' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-info ">Write something</button>
</form>
    <br>
</div>
<div class="container">
<p>Recent Update</p>

<hr>
    {% if  posts  %}
    {% for postingan in posts %}
        <div id="post-comment">

        <h3><img src="https://static.pexels.com/photos/323705/pexels-photo-323705.jpeg"
                 class="profil" width="40" height="40" style="border-radius: 50%;">
            <strong>{{postingan.name}}</strong></h3>

        <p>{{postingan.body}}</p>

        <p>         {{postingan.waktu}}</p>
        <br>
             {% if comments %}

               {% for komentars in comments %}

           {% if postingan.body == komentars.forum.body %}
               <h3>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img src="https://static.pexels.com/photos/323705/pexels-photo-323705.jpeg"
                 class="profil" width="40" height="40" style="border-radius: 50%;">
               {{ postingan.name }}
            </h3>
                 <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{komentars.body}}</p>

        <p>         &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{komentars.waktu}}</p>
        <br>
               {% endif %}

               {% endfor %}

           {% endif %}

       <form method="post" action="{% url 'forum:buildComment' postingan.id %} ">
    {% csrf_token %}
    {{ commentsForm.as_p }}
    <button type="submit" class="btn btn-info ">Comment</button>


</form>
        <br>

        </div>
        {% endfor %}


    {% endif %}
</div>
{% endblock %}

<script type="application/javascript">
   var func=function () {
        $('#post-comment').innerHTML= " <p> Comment </p> ";
    }
</script>
</body>
</html>

wl_login/templates/wl_login.html
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="LAB 5">
    <meta name="author" content="">
    <!-- bootstrap csss -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Droid+Sans:400,700">
 <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.4/css/select2.min.css" rel="stylesheet" />
 <link rel="stylesheet" href="https://code.jquery.com/qunit/qunit-2.4.1.css">
    <title>
    Wyvern Link
    </title>
</head>
<body>
    <header>
    </header>
    <content>
            
    <div class="container">
		<h3> Login Perusahaan </h3>
        <script type="in/Login"></script>
    </div>

    </content>
    <footer>
    </footer>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
	<script type="text/javascript" src="//platform.linkedin.com/in.js">
  		api_key: 818gaq2irb7wty
  		authorize: true
  		onLoad: onLinkedInLoad
	</script>

	<script type="text/javascript">
    
  // Setup an event listener to make an API call once auth is complete
    function onLinkedInLoad() {
      IN.Event.on(IN, "auth", shareContent);
    }

  // Handle the successful return from the API call
  function onSuccess(data) {
    console.log(data);
  }

  // Handle an error response from the API call
  function onError(error) {
    console.log(error);
  }
 // Use the API call wrapper to share content on LinkedIn
  function shareContent() {
        
    // Build the JSON payload containing the content to be shared
    var payload = { 
      "comment": "Check out developer.linkedin.com! http://linkd.in/1FC2PyG", 
      "visibility": { 
        "code": "anyone"
      } 
    };

    var cpnyID = 1234;

    IN.API.Raw("/companies/" + cpnyID + "/shares?format=json")
      .method("POST")
      .body(JSON.stringify(payload))
      .result(onSuccess)
      .error(onError);
  }

</script>

</body>


<!--<header>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <meta charset="UTF-8">
    <title>Profil</title>
	<h1>Login</h1>
</header>
<body align="center">
			<button class="btn btn-info"> LinkIn Login </button
</body>
<footer>
	<h4> Thanks for coming </h4>
</footer> -->
</html
{% endblock %}

wl_profile2/templates/profile/hehe.html
<!DOCTYPE html>
<html>
<head>
<script type="text/javascript" src="//platform.linkedin.com/in.js">
    api_key: 816z2l1p1v9gwv
    authorize: true
    onLoad: onLinkedInLoad
    scope: r_basicprofile r_emailaddress rw_company_admin
</script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

<script type="text/javascript">
    // Setup an event listener to make an API call once auth is complete
    function onLinkedInLoad() {
        IN.Event.on(IN, "auth", getProfileData);
    }

    // Use the API call wrapper to request the member's profile data
    function getProfileData() {
      var cpnyID = 13601418;
      IN.API.Raw("/companies/" + cpnyID + ":(id,name,ticker,description,company-type,founded-year,locations:(address),website-url,square-logo-url,specialties)?format=json").method("GET").result(displayProfileData).error(onError);
    }

    // Handle the successful return from the API call
    function displayProfileData(data){
      $.ajax({
      method: "POST",
      url: '{% url "profile:createModel" %}',
      data: {
        name: data.name,
        specialty: data.specialties.values[0],
        year:data.foundedYear,
        description:data.description,
        website:data.websiteUrl,
        type:data.companyType.name,


      },
      dataType: 'json',
      success: function(company) {
        window.data = data;
        console.log(data);

          $("#name").html("Selamat datang, " +company.company_name);
          $("#CompanyName").html(company.company_name);
          $("#website").html(company.website);
          $("#description").html(company.description);
          $("#founded").html("Founded: " +company.yearFounded);
          $("#specialty").html("Specialty: " +company.specialty)
          $("#type").html(company.type);
          $("#address").html(data.locations.values[0].address.city
          + " " +data.locations.values[0].address.postalCode+ " "+ data.locations.values[0].address.street1);
          $("#picture").html('<img src="'+data.squareLogoUrl+'" />')

          document.getElementById('profileData').style.display = 'block';

      },
      error: function(error) {
        alert("yah error")
      }
      });




    }

    // Handle an error response from the API call
    function onError(error) {
        console.log(error);
    }

    // Destroy the session of linkedin
    function logout(){
        IN.User.logout(removeProfileData);
    }

    // Remove profile data from page
    function removeProfileData(){
        document.getElementById('profileData').remove();
    }
</script>
</head>

<body>
  <!-- sign in with linkedin button -->
<script type="in/Login"></script>

<!-- display profile info -->
<div id="profileData" style="display: none;">
    <p id="name"></p>
    <div id="picture"></div>
    <div class="info">
      <p id="CompanyName"></p>
      <p id="website"></p>
      <p id="specialty"></p>
      <p id="type"></p>
      <p id="founded"></p>
      <p id= "address"> </p>
      <p id="description"></p>
    </div>
    <p><a href="javascript:void(0);" onclick="logout()">Logout</a></p>
</div>
</body>


</html>

wl_profile2/templates/profile/layout/base.html
{% load staticfiles %} {% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <script type="text/javascript" src="//platform.linkedin.com/in.js">
      api_key: 816z2l1p1v9gwv
      authorize: true
      onLoad: onLinkedInLoad
      scope: r_basicprofile r_emailaddress rw_company_admin
  </script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script type="text/javascript">
      // Setup an event listener to make an API call once auth is complete
      function onLinkedInLoad() {
          IN.Event.on(IN, "auth", getProfileData);
      }

      // Use the API call wrapper to request the member's profile data
      function getProfileData() {
        var cpnyID = 13601418;
        IN.API.Raw("/companies/" + cpnyID + ":(id,name,ticker,description,company-type,founded-year,locations:(address),website-url,square-logo-url,specialties)?format=json").method("GET").result(displayProfileData).error(onError);
      }

      // Handle the successful return from the API call
      function displayProfileData(data){
        $.ajax({
        method: "POST",
        url: '{% url "profile:createModel" %}',
        data: {
          name: data.name,
          specialty: data.specialties.values[0],
          year:data.foundedYear,
          description:data.description,
          website:data.websiteUrl,
          type:data.companyType.name,


        },
        dataType: 'json',
        success: function(company) {
          window.data = data;
          console.log(data);

            $("#judul").html(company.company_name);
            $("#CompanyName").html(company.company_name);
            $("#website").html(company.website);
            $("#description").html(company.description);
            $("#founded").html("Founded: " +company.yearFounded);
            $("#specialty").html("Specialty: " +company.specialty)
            $("#type").html(company.type);
            $("#address").html(data.locations.values[0].address.city
            + " " +data.locations.values[0].address.postalCode+ " "+ data.locations.values[0].address.street1);
            $("#logo").html('<img src="'+data.squareLogoUrl+'" />')

            document.getElementById('profileData').style.display = 'block';
            document.getElementById('header').style.display = 'block';
            document.getElementById('footer').style.display = 'block';

        },
        error: function(error) {
          alert("yah error")
        }
        });


      }

      // Handle an error response from the API call
      function onError(error) {
          console.log(error);
      }

      // Destroy the session of linkedin
      function logout(){
          IN.User.logout(removeProfileData);
      }

      // Remove profile data from page
      function removeProfileData(){
          document.getElementById('profileData').remove();
          document.getElementById('header').remove();
          document.getElementById('footer').remove();
      }
  </script>
  <script src="{% static 'js/profile.js' %}"></script>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />


	<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Montserrat:100,100i,200,200i,300,400,400i,500,500i,600,600i,700,700i,800" rel="stylesheet">




  <title>
    {% block title %} Profile {% endblock %}
  </title>
</head>

<body>
  <header id="header" style="display: none;">
    {% include "profile/partials/header.html" %}
  </header>
  <content>
    {% block content %}
    <!-- content goes here -->
    {% endblock %}
  </content>
  <footer id='footer' style="display: none;">
    <!-- TODO Block Footer dan include footer.html -->
    {% block footer %} {% include "profile/partials/footer.html" %} {% endblock %}
  </footer>
  <!-- Jquery n Bootstrap Script -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  {% block javascript %} {% endblock %}
</body>
</html>

wl_profile2/templates/profile/partials/footer.html
  <div class="container">
    <div class="nine columns">
      <p>Created with love by Origin Masters</p>
    </div>
    <div class="three columns"> <span class="typcn typcn-social-facebook-circular socialIcons"></span> <span class="typcn typcn-social-instagram-circular socialIcons"></span> <span class="typcn typcn-social-google-plus-circular socialIcons"></span> <span class="typcn typcn-social-linkedin-circular socialIcons"></span> </div>
  </div>

wl_profile2/templates/profile/partials/header.html
  <div class="main_nav">
    <div class="container">
      <div class="mobile-toggle"> <span></span> <span></span> <span></span> </div>
      <nav>
        <ul>
          <li><a class="smoothscroll" href="#header">Cari Mahasiswa</a></li>
          <li><a class="smoothscroll" href="#about">Forum</a></li>
          <li><a class="smoothscroll" href="javascript:void(0);" onclick="logout()">Logout</a></li>

        </ul>
      </nav>
    </div>
  </div>
  <div class="title">
    <div><span class="typcn typcn-heart-outline icon heading" id="logo"></span></div>
    <div class="smallsep heading"></div>
    <h1 class="heading" id="judul"></h1>
    <h2 class="heading">Ini Tagline Kita</h2>
    <a class="smoothscroll" href="#about">
    <div class="mouse">
      <div class="wheel"></div>
    </div>
    </a> </div>
  <a class="smoothscroll" href="#about">
  <div class="scroll-down"></div>
  </a>

wl_profile2/templates/profile/profile.html
{% extends "profile/layout/base.html" %}
{% block content %}



  <!-- sign in with linkedin button -->
<script type="in/Login"></script>

<!-- display profile info -->
<div id="profileData" style="display: none;">
<section id="about">
  <div class="container">
    <div class="row">
      <h1>About</h1>
      <div class="block"></div>
      <p id="description"></p>
    </div>
    <div class="row">
      <div class="six columns">
        {% load static %}
        <h3><span class="typcn typcn-device-desktop icon"><img class="img-valign" src="{% static "images/like.png" %}"></span>Brief description</h3>
        <p id="specialty"></p>
        <p id="type"></p>
        <p id="founded"></p>
      </div>

      <div class="six columns">
        <h3><span class="typcn typcn-pen icon"><img class="img-valign" src="{% static "images/time.png" %}"></span>Our History</h3>
        <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</p>
      </div>
      <div class="row">
        <div class="six columns">
          <h3><span class="typcn typcn-cog-outline icon"><img class="img-valign" src="{% static "images/mails.png" %}"></span>Reach us</h3>
          <p id="website"></p>
          <p id="address"></p>

        </div>

      </div>
    </div>
  </div>
</section>
</div>






{% endblock %}